# Generated by Django 5.1 on 2024-08-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=500)),
                ('Reciever', models.CharField(max_length=500)),
                ('Subject', models.CharField(blank=True, max_length=500, null=True)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
