# Generated by Django 5.1 on 2024-08-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msgID',
            field=models.CharField(default=12345, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('msgID',)},
        ),
    ]
