# Generated by Django 5.1 on 2024-08-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message_msgid_alter_message_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Message',
            field=models.CharField(max_length=10000),
        ),
    ]
