# Generated by Django 5.1 on 2024-08-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Message',
            field=models.CharField(max_length=15000),
        ),
    ]
